services:
  app:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    working_dir: /workspace/sample/APISpecification
    volumes:
      - ./workspace:/workspace:cached
      - ./mkdocs-hooks:/mkdocs-hooks:ro
    command: mkdocs serve -a 0.0.0.0:8000
    ports:
      - "38000:8000"
    depends_on:
      - plantuml
    networks:
      - mkdocs-net

  plantuml:
    image: plantuml/plantuml-server:jetty
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - mkdocs-net

networks:
  mkdocs-net:
    driver: bridge
