version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../workspace:/workspace:cached
      - ../mkdocs-hooks:/mkdocs-hooks:ro
    command: sleep infinity
    depends_on:
      - plantuml
      - kroki
    networks:
      - mkdocs-net

  plantuml:
    image: plantuml/plantuml-server:jetty
    expose:
      - "8080"
    networks:
      - mkdocs-net

  kroki:
    image: yuzutech/kroki
    depends_on:
      - mermaid
    environment:
      KROKI_MERMAID_HOST: mermaid
    expose:
      - "8000"
    networks:
      - mkdocs-net

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
    networks:
      - mkdocs-net

networks:
  mkdocs-net:
    driver: bridge
